baseURL: "https://imdevinc.com/"
languageCode: "en-us"
title: "ImDevinC"
theme: "papermod"

googleAnalytics: G-9HCG8CTRP1

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "ImDevinC"
  description: "Code, games, and more"
  keywords: [blog, portfolio, code, kubernetes, docker]
  author: Me
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showToc: false
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: ""
    favicon16x16: ""
    favicon32x32: ""
    apple_touch_icon: ""
    safari_pinned_tab: ""

  profileMode:
    enabled: false
    title: ImDevinC
    buttons:
      - name: Posts
        url: posts

  homeInfoParams:
    Title: "Hi there! \U0001F44B. I'm Devin C."
    Content: I'm a guy (he/him) that likes to explore new technology, collect hobbies, and occasionally talk about them.

  socialIcons:
    - name: twitter
      url: https://twitter.com/ImDevinC
    - name: github
      url: https://github.com/ImDevinC
    - name: email
      url: mailto:me@imdevinc.com
    - name: 'other'
      url: https://keys.openpgp.org/vks/v1/by-fingerprint/A69D9C27016EDE8E90F6B13013A7F3711AFD51AA

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
