FROM node:16

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

ENV PATH=$PATH:/home/node/.npm-global/bin

RUN npm install -g resume-cli

WORKDIR /usr/src

RUN npm install jsonresume-theme-rocketspacer

WORKDIR /usr/src/app

ENTRYPOINT ["npx", "resume"]
