name: Publish changes to the server

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - "terraform/**"
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Generate static assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Generate assets
        id: generate
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: latest

      - name: Extract assets
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.generate.outputs.digest }}
          path: usr/src/app/public/.

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: imdevinc-site
          source_dir: ${{ steps.extract.outputs.destination }}
          destination_dir: ''