name: Publish changes to the server

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "static/**"
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Upload to S3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate resume
        id: build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: latest
          file: Dockerfile.resume      
      - name: Generate resume
        id: generate
        run: docker run -v $PWD/static:/usr/src/app ${{ steps.build.outputs.digest }} export resume.html --theme jsonresume-theme-rocketspacer
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: imdevinc-site
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: ./static