name: Publish changes to the server

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "static/**"
    
jobs:
  resume:
    runs-on: ubuntu-latest
    name: Update resume
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate resume
        id: generate
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: latest
          file: Dockerfile.resume
      - name: Copy resume
        id: copy
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.generate.outputs.digest }}
          path: /usr/src/app/resume.html
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: imdevinc-site
          source_dir: ${{ steps.copy.outputs.destination }}
          destination_dir: ''

  publish:
    if: ${{ always() }}
    needs: [ resume ]
    runs-on: ubuntu-latest
    name: Upload to S3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: imdevinc-site
          source_dir: static
          destination_dir: ''
