name: Publish changes to the server

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "static/**"
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Generate static assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: imdevinc-site
          source_dir: static
          destination_dir: ''
