name: Publish changes to the server

on:
  push:
    branches:
      - main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Generate static assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Generate assets
        id: generate
        uses: docker/build-push-action@v2
        with:
          push: false
          repository: blog-image
          tags: ubuntu-latest

      - name: Extract assets
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.generate.outputs.digest }}
          path: usr/src/app/public/.
        
      - name: Publish files
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ${{ steps.extract.outputs.destination }}/.
          target: "/var/www/imdevinc.com"
